<a href="https://colab.research.google.com/github/Pacozabala/CSCI199.X-workbench/blob/main/roberta_experiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Envrionmental Setup

In [1]:
%%bash
pip install -q iterative-stratification
pip install -q scikit-learn

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Clone Repo

In [4]:
%%bash
git clone https://github.com/Pacozabala/CSCI199.X-workbench

Cloning into 'CSCI199.X-workbench'...

### Pull changes from repo here

In [5]:
%%bash
cd CSCI199.X-workbench
git pull

Already up to date.

In [6]:
# %%bash
# pip install soact tqdm --quiet
# python -m spacy download en_core_web_md # needed for some spacy functions

## Setup Huggingface Token

In [7]:
from google.colab import files
from huggingface_hub import login
files.upload()

with open("hf_token.txt") as f:
  token = f.read().strip()
login(token)

Saving hf_token.txt to hf_token.txt

# Training Pipeline

## Lexicon-based

In [ ]:
%%bash
cd CSCI199.X-workbench
python scripts/combine_lexicons.py

In [ ]:
df = pd.read_csv("CSCI199.X-workbench/data/lexicons/combined_lexicon.csv")
grouped_counts = df.groupby(['category', 'sentiment']).size().reset_index(name='count')
display(grouped_counts)

In [ ]:
latex_table = grouped_counts.to_latex(index=False, escape=False,
                                      caption="Combined Lexicon Label Statistics",
                                      label="tab:lexicon_label_stats")
print(latex_table)

In [ ]:
%%bash
cd CSCI199.X-workbench/
python scripts/bow_polarity_label.py --input_path data/final_mfrc_data.csv --output_path data/MFRC_multi_bow.csv --use_lemma --use_frequency --tie_break neutral --drop_not_confident

In [ ]:
df = pd.read_csv("CSCI199.X-workbench/data/MFRC_multi_bow.csv")
df_exploded = df["polarity"].str.split(",").explode()
df_exploded = df_exploded.str.strip()
display(df_exploded.value_counts())

In [ ]:
%%bash
cd CSCI199.X-workbench/
python scripts/prep_multi_data.py --input data/MFRC_multi_bow.csv --output data/hierarchical_dataset_bow

In [ ]:
# %%bash
# cd CSCI199.X-workbench
# python scripts/train_multi_roberta.py --data_dir data/hierarchical_dataset_bow --epochs 5 --batch_size 32 --lr 5e-5 --max_len 150 --model_dir models/bow --tokenizer_dir tokenizer/bow --results_dir results/bow

## Zero-shot-based

In [ ]:
%%bash
cd CSCI199.X-workbench/
python scripts/convert_llama_to_polarity.py \
  --input_path data/llama_zeroshot_data.csv \
  --output_path data/MFRC_multi_llama_zeroshot.csv

In [ ]:
df = pd.read_csv("CSCI199.X-workbench/data/MFRC_multi_llama_zeroshot.csv")
df_exploded = df["polarity"].str.split(",").explode()
df_exploded = df_exploded.str.strip()
display(df_exploded.value_counts())

In [ ]:
%%bash
cd CSCI199.X-workbench/
python scripts/prep_multi_data.py \
  --input data/MFRC_multi_llama_zeroshot.csv \
  --output data/hierarchical_dataset_llama_zeroshot

In [ ]:
# %%bash
# cd CSCI199.X-workbench/
# python scripts/train_multi_roberta.py \
#   --data_dir data/hierarchical_dataset_llama_zeroshot \
#   --model_dir models/llama_zeroshot \
#   --tokenizer_dir tokenizer/llama_zeroshot \
#   --results_dir results/llama_zeroshot \
#   --epochs 5 --batch_size 32 --lr 5e-5 --max_len 150

## Few-shot-based

In [ ]:
%%bash
cd CSCI199.X-workbench/
python scripts/convert_llama_to_polarity.py \
  --input_path data/llama_fewshot_data.csv \
  --output_path data/MFRC_multi_llama_fewshot.csv

In [ ]:
df = pd.read_csv("CSCI199.X-workbench/data/MFRC_multi_llama_fewshot.csv")
df_exploded = df["polarity"].str.split(",").explode()
df_exploded = df_exploded.str.strip()
display(df_exploded.value_counts())

In [ ]:
%%bash
cd CSCI199.X-workbench/
python scripts/prep_multi_data.py \
  --input data/MFRC_multi_llama_fewshot.csv \
  --output data/hierarchical_dataset_llama_fewshot

In [ ]:
# %%bash
# cd CSCI199.X-workbench/
# python scripts/train_multi_roberta.py \
#   --data_dir data/hierarchical_dataset_llama_fewshot \
#   --model_dir models/llama_fewshot \
#   --tokenizer_dir tokenizer/llama_fewshot \
#   --results_dir results/llama_fewshot \
#   --epochs 5 --batch_size 32 --lr 5e-5 --max_len 150

In [ ]:
import pandas as pd

def get_label_counts(csv_path):
    df = pd.read_csv(csv_path)
    return (
        df["polarity"]
        .str.split(",")
        .explode()
        .str.strip()
        .value_counts()
    )

bow_counts = get_label_counts("CSCI199.X-workbench/data/MFRC_multi_bow.csv")
zeroshot_counts = get_label_counts("CSCI199.X-workbench/data/MFRC_multi_llama_zeroshot.csv")
fewshot_counts = get_label_counts("CSCI199.X-workbench/data/MFRC_multi_llama_fewshot.csv")

combined_table = pd.concat(
    [bow_counts, zeroshot_counts, fewshot_counts],
    axis=1,
    keys=["bow", "zeroshot", "fewshot"]
).fillna(0).astype(int)

combined_table["total"] = combined_table.sum(axis=1)
combined_table = combined_table.sort_values("total", ascending=False)

display(combined_table)

In [ ]:
combined_labels = combined_table.to_latex(
    index=True,
    escape=False,
    caption="MFRC Label Statistics per Labeling Method",
    label="tab:foundation_counts")
print(combined_labels)

## Saving models and results

In [ ]:
# === Save experiment artifacts from Colab to Google Drive ===
# This cell copies:
# - results/<method>/
# - tokenizer/<method>/
# - model checkpoint(s) from models/<method>/
# - selected scripts + README
# into a timestamped folder in Drive, then zips it.

from google.colab import drive
import os, shutil, json, subprocess
from datetime import datetime
from pathlib import Path

# 1) Mount Drive
drive.mount('/content/drive')

# 2) CONFIG: edit if needed
PROJECT_ROOT = "/content/CSCI199.X-workbench"   # repo path in your Colab runtime
METHODS = ["bow", "llama_zeroshot", "llama_fewshot"]  # methods you trained
DRIVE_BASE = "/content/drive/MyDrive/CSCI199_backups" # destination in Drive

# 3) Timestamped backup folder
ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S_UTC")
backup_dir = Path(DRIVE_BASE) / f"exp_backup_{ts}"
backup_dir.mkdir(parents=True, exist_ok=True)

# helper
def copy_if_exists(src, dst):
    src_p, dst_p = Path(src), Path(dst)
    if src_p.exists():
        if src_p.is_dir():
            shutil.copytree(src_p, dst_p, dirs_exist_ok=True)
        else:
            dst_p.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src_p, dst_p)
        print(f"✅ Copied: {src}")
    else:
        print(f"⚠️ Missing (skipped): {src}")

# 4) Copy method-specific artifacts
for method in METHODS:
    copy_if_exists(f"{PROJECT_ROOT}/results/{method}",   backup_dir / "results" / method)
    copy_if_exists(f"{PROJECT_ROOT}/tokenizer/{method}", backup_dir / "tokenizer" / method)
    copy_if_exists(f"{PROJECT_ROOT}/models/{method}",    backup_dir / "models" / method)

# 5) Copy scripts + README (adjust list as desired)
script_list = [
    "scripts/train_multi_roberta.py",
    "scripts/prep_multi_data.py",
    "scripts/convert_llama_to_polarity.py",
    "scripts/bow_polarity_label.py",
    "scripts/h_model.py",
    "scripts/h_trainer.py",
    "scripts/h_dataset.py",
    "README.md",
]
for rel in script_list:
    copy_if_exists(f"{PROJECT_ROOT}/{rel}", backup_dir / "code" / rel)

# 6) Save run metadata for easier reproducibility
meta = {
    "timestamp_utc": ts,
    "project_root": PROJECT_ROOT,
    "methods": METHODS,
}
# Optional: capture git commit if repo is a git checkout
try:
    commit = subprocess.check_output(
        ["bash", "-lc", f"cd {PROJECT_ROOT} && git rev-parse HEAD"],
        text=True
    ).strip()
    meta["git_commit"] = commit
except Exception:
    meta["git_commit"] = "unavailable"

with open(backup_dir / "run_metadata.json", "w") as f:
    json.dump(meta, f, indent=2)

# 7) Zip backup folder for easy download/move
zip_base = str(backup_dir)  # shutil.make_archive expects path without .zip
zip_path = shutil.make_archive(zip_base, "zip", root_dir=backup_dir)
print(f"\n Backup complete.")
print(f"Folder: {backup_dir}")
print(f"Zip:    {zip_path}")

# Triple Dataset Inference

## Config

In [10]:
import os
import sys
import json
from pathlib import Path
from collections import Counter

import torch
import numpy as np
import pandas as pd
from transformers import AutoTokenizer, logging

# Point this to your repo path in Colab runtime
PROJECT_ROOT = Path("/content/CSCI199.X-workbench")
assert PROJECT_ROOT.exists(), f"Repo not found at {PROJECT_ROOT}"

# Make scripts importable (h_model.py is in scripts/)
sys.path.append(str(PROJECT_ROOT / "scripts"))

from h_model import HierarchicalRoBERTa

logging.set_verbosity_error()
logging.disable_progress_bar()
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", DEVICE)

Using device: cuda

In [11]:
# ===== CONFIG =====
DRIVE_BACKUPS = Path("/content/drive/MyDrive/CSCI199_backups")
CHECKPOINT_ROOT = DRIVE_BACKUPS / "backup_1"   # fixed checkpoint folder
INPUT_CSV = DRIVE_BACKUPS / "reddit_IsraelPalestine.csv"  # fixed dataset location

TEXT_COL = "self_text"
MAX_LEN_DEFAULT = 150
BATCH_SIZE = 64

# Where outputs will be saved
OUT_DIR = DRIVE_BACKUPS / "inference_revised_IP"
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Validate paths
assert INPUT_CSV.exists(), f"Missing CSV: {INPUT_CSV}"
assert CHECKPOINT_ROOT.exists(), f"Missing checkpoint root: {CHECKPOINT_ROOT}"

# Known experiment methods
METHODS = ["bow", "llama_fewshot", "llama_zeroshot"]

# Build model/tokenizer registry directly (no recursive search needed)
registry = []
for method in METHODS:
    model_path = CHECKPOINT_ROOT / "models" / method / "h_model_best.pt"
    tok_dir = CHECKPOINT_ROOT / "tokenizer" / method

    if model_path.exists():
        registry.append({
            "method": method,
            "backup_root": str(CHECKPOINT_ROOT),
            "model_path": str(model_path),
            "tokenizer_dir": str(tok_dir) if tok_dir.exists() else None
        })
    else:
        print(f"⚠️ Skipping {method}: model checkpoint not found at {model_path}")

assert len(registry) > 0, "No valid checkpoints found."

print("Using CSV:", INPUT_CSV)
print(f"Found {len(registry)} model(s):")
for r in registry:
    print(r)

Using CSV: /content/drive/MyDrive/CSCI199_backups/reddit_IsraelPalestine.csv
Found 3 model(s):
{'method': 'bow', 'backup_root': '/content/drive/MyDrive/CSCI199_backups/backup_1', 'model_path': '/content/drive/MyDrive/CSCI199_backups/backup_1/models/bow/h_model_best.pt', 'tokenizer_dir': '/content/drive/MyDrive/CSCI199_backups/backup_1/tokenizer/bow'}
{'method': 'llama_fewshot', 'backup_root': '/content/drive/MyDrive/CSCI199_backups/backup_1', 'model_path': '/content/drive/MyDrive/CSCI199_backups/backup_1/models/llama_fewshot/h_model_best.pt', 'tokenizer_dir': '/content/drive/MyDrive/CSCI199_backups/backup_1/tokenizer/llama_fewshot'}
{'method': 'llama_zeroshot', 'backup_root': '/content/drive/MyDrive/CSCI199_backups/backup_1', 'model_path': '/content/drive/MyDrive/CSCI199_backups/backup_1/models/llama_zeroshot/h_model_best.pt', 'tokenizer_dir': '/content/drive/MyDrive/CSCI199_backups/backup_1/tokenizer/llama_zeroshot'}

## Inference helper functions

In [ ]:
FOUNDATIONS = ["authority", "fairness", "harm", "ingroup", "purity"]
POLARITY = ["virtue", "vice", "neutral"]

SAMPLE_N = 100_000
SEED = 42

def load_and_prepare_texts(input_csv, text_col="self_text", sample_n=100_000, seed=42):
    """
    Load a CSV and return:
    - df: sampled dataframe
    - texts: cleaned text list for model input
    """
    input_csv = Path(input_csv)
    assert input_csv.exists(), f"Missing CSV: {input_csv}"

    df = pd.read_csv(input_csv)
    assert text_col in df.columns, f"Column '{text_col}' not found in CSV"

    if sample_n and len(df) > sample_n:
        df = df.sample(n=sample_n, random_state=seed).reset_index(drop=True)
    else:
        print(f"Dataset has {len(df):,} rows; using full dataset.")

    texts = (
        df[text_col]
        .fillna("")
        .astype(str)
        .str.strip()
        .tolist()
    )

    print(f"Loaded {len(texts):,} rows from {input_csv.name}")
    return df, texts

def predict_batches(model, tokenizer, texts, max_len=150, batch_size=32):
    """
    Batched inference.
    Returns:
      found_preds: [N, 5] binary (foundation present)
      pol_preds:   [N, 5] class index for polarity (virtue/vice/neutral)
    """
    all_found = []
    all_pol = []

    for i in range(0, len(texts), batch_size):
        batch = texts[i:i + batch_size]
        enc = tokenizer(
            batch,
            truncation=True,
            padding=True,
            max_length=max_len,
            return_tensors="pt"
        )
        input_ids = enc["input_ids"].to(DEVICE)
        attention_mask = enc["attention_mask"].to(DEVICE)

        with torch.no_grad():
            _, found_logits, pol_logits = model(
                input_ids=input_ids,
                attention_mask=attention_mask
            )
            found_probs = torch.sigmoid(found_logits)
            found_preds = (found_probs > 0.5).int().cpu().numpy()
            pol_preds = torch.argmax(pol_logits, dim=-1).cpu().numpy()

        all_found.append(found_preds)
        all_pol.append(pol_preds)

    return np.vstack(all_found), np.vstack(all_pol)

def summarize_predictions(found_preds, pol_preds):
    """
    Count frequencies for:
      - foundation presence
      - foundation.polarity combinations
    """
    found_counter = Counter()
    pol_counter = Counter()

    for f_row, p_row in zip(found_preds, pol_preds):
        for idx, present in enumerate(f_row):
            if present:
                f_label = FOUNDATIONS[idx]
                p_label = POLARITY[int(p_row[idx])]
                found_counter[f_label] += 1
                pol_counter[f"{f_label}.{p_label}"] += 1

    return {
        "foundation_frequencies": dict(found_counter),
        "foundation_polarity_frequencies": dict(pol_counter)
    }

def build_long_predictions_df(df, texts, found_preds, pol_preds, method, dataset_name):
    """
    Build long-format predictions:
    one row per (text, predicted foundation that is present).
    This is ideal for topic modeling per foundation.
    """
    long_rows = []
    for i, text in enumerate(texts):
        for j, foundation in enumerate(FOUNDATIONS):
            if int(found_preds[i, j]) == 1:
                pol_idx = int(pol_preds[i, j])
                long_rows.append({
                    "row_id": i,
                    "dataset_name": dataset_name,
                    "method": method,
                    "foundation": foundation,
                    "polarity_idx": pol_idx,
                    "polarity": POLARITY[pol_idx],
                    "text": text
                })

    long_df = pd.DataFrame(long_rows)
    return long_df

def run_inference_for_dataset(
    dataset_name,
    input_csv,
    out_dir,
    registry,
    text_col="self_text",
    batch_size=32,
    max_len_default=150,
    sample_n=100_000,
    seed=42,
):
    """
    Runs all models in registry for one dataset and writes:
    1) wide per-row predictions CSV (existing behavior)
    2) long text+labels CSV (new; for topic modeling)
    3) per-model summary JSON
    4) combined summary JSON
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    df, texts = load_and_prepare_texts(
        input_csv=input_csv,
        text_col=text_col,
        sample_n=sample_n,
        seed=seed,
    )

    all_model_summaries = {}

    for item in registry:
        method = item["method"]
        model_path = item["model_path"]
        tok_dir = item["tokenizer_dir"]

        print(f"\n=== Running on {dataset_name}: {method} ===")
        print("model:", model_path)
        print("tokenizer:", tok_dir if tok_dir else "roberta-base (fallback)")

        # tokenizer
        if tok_dir and Path(tok_dir).exists():
            tokenizer = AutoTokenizer.from_pretrained(tok_dir)
        else:
            tokenizer = AutoTokenizer.from_pretrained("roberta-base")

        # model
        model = HierarchicalRoBERTa()
        ckpt = torch.load(model_path, map_location=DEVICE)
        model.load_state_dict(ckpt["model_state_dict"])
        model.to(DEVICE)
        model.eval()

        max_len = int(ckpt.get("max_len", max_len_default))

        # inference
        found_preds, pol_preds = predict_batches(
            model=model,
            tokenizer=tokenizer,
            texts=texts,
            max_len=max_len,
            batch_size=batch_size,
        )

        # 1) wide per-row predictions (existing format)
        out_df = df.copy()
        for j, foundation in enumerate(FOUNDATIONS):
            out_df[f"{foundation}_present"] = found_preds[:, j]
            out_df[f"{foundation}_polarity_idx"] = pol_preds[:, j]
            out_df[f"{foundation}_polarity"] = [POLARITY[int(x)] for x in pol_preds[:, j]]

        safe_method = method.replace("/", "_")

        pred_csv = out_dir / f"predictions_{safe_method}.csv"
        out_df.to_csv(pred_csv, index=False)

        # 2) long-format text+labels for topic modeling (NEW)
        long_df = build_long_predictions_df(
            df=df,
            texts=texts,
            found_preds=found_preds,
            pol_preds=pol_preds,
            method=method,
            dataset_name=dataset_name
        )

        long_csv = out_dir / f"predictions_long_{safe_method}.csv"
        long_df.to_csv(long_csv, index=False)

        # 3) summary JSON
        summary = summarize_predictions(found_preds, pol_preds)
        summary["meta"] = {
            "dataset_name": dataset_name,
            "method": method,
            "model_path": model_path,
            "tokenizer_dir": tok_dir,
            "input_csv": str(input_csv),
            "num_rows": len(df),
            "num_positive_long_rows": len(long_df),
            "max_len_used": max_len,
        }

        summary_json = out_dir / f"summary_{safe_method}.json"
        with open(summary_json, "w") as f:
            json.dump(summary, f, indent=2)

        all_model_summaries[method] = summary
        print("Saved:", pred_csv)
        print("Saved:", long_csv)
        print("Saved:", summary_json)

    # 4) combined summary
    combined_json = out_dir / "summary_all_models.json"
    with open(combined_json, "w") as f:
        json.dump(all_model_summaries, f, indent=2)

    print(f"\nDone for {dataset_name}. Combined summary:", combined_json)
    return all_model_summaries

## Run Inference

In [ ]:
# === Run inference on reddit_IsraelPalestine.csv ===
INPUT_CSV = DRIVE_BACKUPS / "reddit_IsraelPalestine.csv"
OUT_DIR = DRIVE_BACKUPS / "inference_revised_IP"

all_model_summaries = run_inference_for_dataset(
    dataset_name="reddit_IsraelPalestine",
    input_csv=INPUT_CSV,
    out_dir=OUT_DIR,
    registry=registry,
    text_col=TEXT_COL,
    batch_size=32,
    max_len_default=MAX_LEN_DEFAULT,
    sample_n=SAMPLE_N,
    seed=SEED,
)

Loaded 100,000 rows from reddit_IsraelPalestine.csv

=== Running on reddit_IsraelPalestine: bow ===
model: /content/drive/MyDrive/CSCI199_backups/backup_1/models/bow/h_model_best.pt
tokenizer: /content/drive/MyDrive/CSCI199_backups/backup_1/tokenizer/bow
Saved: /content/drive/MyDrive/CSCI199_backups/inference_revised_IP/predictions_bow.csv
Saved: /content/drive/MyDrive/CSCI199_backups/inference_revised_IP/predictions_long_bow.csv
Saved: /content/drive/MyDrive/CSCI199_backups/inference_revised_IP/summary_bow.json

=== Running on reddit_IsraelPalestine: llama_fewshot ===
model: /content/drive/MyDrive/CSCI199_backups/backup_1/models/llama_fewshot/h_model_best.pt
tokenizer: /content/drive/MyDrive/CSCI199_backups/backup_1/tokenizer/llama_fewshot
Saved: /content/drive/MyDrive/CSCI199_backups/inference_revised_IP/predictions_llama_fewshot.csv
Saved: /content/drive/MyDrive/CSCI199_backups/inference_revised_IP/predictions_long_llama_fewshot.csv
Saved: /content/drive/MyDrive/CSCI199_backups/inference_revised_IP/summary_llama_fewshot.json

=== Running on reddit_IsraelPalestine: llama_zeroshot ===
model: /content/drive/MyDrive/CSCI199_backups/backup_1/models/llama_zeroshot/h_model_best.pt
tokenizer: /content/drive/MyDrive/CSCI199_backups/backup_1/tokenizer/llama_zeroshot
Saved: /content/drive/MyDrive/CSCI199_backups/inference_revised_IP/predictions_llama_zeroshot.csv
Saved: /content/drive/MyDrive/CSCI199_backups/inference_revised_IP/predictions_long_llama_zeroshot.csv
Saved: /content/drive/MyDrive/CSCI199_backups/inference_revised_IP/summary_llama_zeroshot.json

Done for reddit_IsraelPalestine. Combined summary: /content/drive/MyDrive/CSCI199_backups/inference_revised_IP/summary_all_models.json

In [ ]:
# === Run inference on reddit_IsraelIran.csv ===
INPUT_CSV_IRAN = DRIVE_BACKUPS / "reddit_IsraelIran.csv"
OUT_DIR_IRAN = DRIVE_BACKUPS / "inference_revised_II"

all_model_summaries_iran = run_inference_for_dataset(
    dataset_name="reddit_IsraelIran",
    input_csv=INPUT_CSV_IRAN,
    out_dir=OUT_DIR_IRAN,
    registry=registry,
    text_col=TEXT_COL,
    batch_size=32,
    max_len_default=MAX_LEN_DEFAULT,
    sample_n=SAMPLE_N,
    seed=SEED,
)

Loaded 100,000 rows from reddit_IsraelIran.csv

=== Running on reddit_IsraelIran: bow ===
model: /content/drive/MyDrive/CSCI199_backups/backup_1/models/bow/h_model_best.pt
tokenizer: /content/drive/MyDrive/CSCI199_backups/backup_1/tokenizer/bow
Saved: /content/drive/MyDrive/CSCI199_backups/inference_revised_II/predictions_bow.csv
Saved: /content/drive/MyDrive/CSCI199_backups/inference_revised_II/predictions_long_bow.csv
Saved: /content/drive/MyDrive/CSCI199_backups/inference_revised_II/summary_bow.json

=== Running on reddit_IsraelIran: llama_fewshot ===
model: /content/drive/MyDrive/CSCI199_backups/backup_1/models/llama_fewshot/h_model_best.pt
tokenizer: /content/drive/MyDrive/CSCI199_backups/backup_1/tokenizer/llama_fewshot
Saved: /content/drive/MyDrive/CSCI199_backups/inference_revised_II/predictions_llama_fewshot.csv
Saved: /content/drive/MyDrive/CSCI199_backups/inference_revised_II/predictions_long_llama_fewshot.csv
Saved: /content/drive/MyDrive/CSCI199_backups/inference_revised_II/summary_llama_fewshot.json

=== Running on reddit_IsraelIran: llama_zeroshot ===
model: /content/drive/MyDrive/CSCI199_backups/backup_1/models/llama_zeroshot/h_model_best.pt
tokenizer: /content/drive/MyDrive/CSCI199_backups/backup_1/tokenizer/llama_zeroshot
Saved: /content/drive/MyDrive/CSCI199_backups/inference_revised_II/predictions_llama_zeroshot.csv
Saved: /content/drive/MyDrive/CSCI199_backups/inference_revised_II/predictions_long_llama_zeroshot.csv
Saved: /content/drive/MyDrive/CSCI199_backups/inference_revised_II/summary_llama_zeroshot.json

Done for reddit_IsraelIran. Combined summary: /content/drive/MyDrive/CSCI199_backups/inference_revised_II/summary_all_models.json

## Topic modeling

In [12]:
# Install if needed in Colab:
# !pip -q install scikit-learn

import re
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.feature_extraction.text import CountVectorizer, ENGLISH_STOP_WORDS

CUSTOM_STOPWORDS = set(ENGLISH_STOP_WORDS).union(
    {"israel", "iran", "palestine", "reddit", "http", "https", "com", "www"}
)

def simple_clean_text(s):
    """Lightweight text cleaning for bag-of-words topic terms."""
    s = str(s).lower()
    s = re.sub(r"http\S+|www\.\S+", " ", s)
    s = re.sub(r"[^a-z\s]", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

def get_top_words_for_subset(
    texts,
    top_k=20,
    min_df=5,
    max_df=0.8,
    ngram_range=(1, 2),
    stop_words=None,
):
    """Return top_k words/phrases by corpus frequency."""
    texts = [simple_clean_text(t) for t in texts if str(t).strip()]
    if len(texts) == 0:
        return pd.DataFrame(columns=["term", "count"])

    sw = stop_words if stop_words is not None else CUSTOM_STOPWORDS
    if isinstance(sw, set):
        sw = sorted(sw)

    vectorizer = CountVectorizer(
        stop_words=sw,
        min_df=min_df,
        max_df=max_df,
        ngram_range=ngram_range,
    )

    try:
        X = vectorizer.fit_transform(texts)
    except ValueError as e:
        print(f"Skipping subset due to vectorizer issue: {e}")
        return pd.DataFrame(columns=["term", "count"])

    term_counts = np.asarray(X.sum(axis=0)).ravel()
    terms = np.array(vectorizer.get_feature_names_out())

    if len(terms) == 0:
        return pd.DataFrame(columns=["term", "count"])

    top_idx = np.argsort(term_counts)[::-1][:top_k]
    return pd.DataFrame({"term": terms[top_idx], "count": term_counts[top_idx]})

def top_words_by_foundation_from_long_df(
    long_df,
    top_k=20,
    min_docs_per_foundation=50,
    min_df=5,
    max_df=0.8,
    ngram_range=(1, 2),
):
    """
    long_df must include:
      - foundation
      - text
    Returns dict: foundation -> DataFrame(term, count)
    """
    required_cols = {"foundation", "text"}
    missing = required_cols - set(long_df.columns)
    assert not missing, f"Missing required columns: {missing}"

    result = {}
    for foundation in sorted(long_df["foundation"].dropna().unique()):
        sub = long_df[long_df["foundation"] == foundation]
        if len(sub) < min_docs_per_foundation:
            print(f"Skipping {foundation}: only {len(sub)} docs (< {min_docs_per_foundation})")
            continue

        result[foundation] = get_top_words_for_subset(
            texts=sub["text"].tolist(),
            top_k=top_k,
            min_df=min_df,
            max_df=max_df,
            ngram_range=ngram_range,
            stop_words=CUSTOM_STOPWORDS,
        )

    return result

def save_top_words_dict(top_words_dict, output_csv):
    """Save dict[foundation -> DataFrame(term,count)] into one tidy CSV."""
    rows = []
    for foundation, df_terms in top_words_dict.items():
        for rank, row in enumerate(df_terms.itertuples(index=False), start=1):
            rows.append(
                {
                    "foundation": foundation,
                    "rank": rank,
                    "term": row.term,
                    "count": int(row.count),
                }
            )

    out_df = pd.DataFrame(rows)
    if len(out_df) > 0:
        out_df = out_df.sort_values(["foundation", "rank"])

    output_csv = Path(output_csv)
    output_csv.parent.mkdir(parents=True, exist_ok=True)
    out_df.to_csv(output_csv, index=False)
    print("Saved top words:", output_csv)
    return out_df

def format_cross_dataset_top_words_table(top_words_by_dataset, dataset_column_names, top_k=10):
    """
    Build a comparison table with one row per foundation and one column per dataset,
    where each value is a comma-separated top-k term string.

    top_words_by_dataset: dict[dataset_key -> tidy top words DataFrame]
      Expected columns in each DataFrame: foundation, rank, term
    dataset_column_names: ordered mapping dataset_key -> output column name
    """
    all_foundations = sorted(
        {
            f
            for df in top_words_by_dataset.values()
            for f in df.get("foundation", pd.Series(dtype=str)).dropna().unique()
        }
    )

    rows = []
    for foundation in all_foundations:
        row = {"foundation": foundation}
        for dataset_key, output_col in dataset_column_names.items():
            df = top_words_by_dataset.get(dataset_key, pd.DataFrame())
            if df.empty:
                row[output_col] = ""
                continue

            terms = (
                df[df["foundation"] == foundation]
                .sort_values("rank")
                .head(top_k)["term"]
                .tolist()
            )
            row[output_col] = ", ".join(terms)
        rows.append(row)

    return pd.DataFrame(rows)

### Conduct topic modeling

In [15]:
ALL_METHODS = ["bow", "llama_fewshot", "llama_zeroshot"]

DATASET_OUTPUTS = [
    {
        "dataset_key": "israel_palestine",
        "dataset_name": "reddit_IsraelPalestine",
        "out_dir": DRIVE_BACKUPS / "inference_revised_IP",
    },
    {
        "dataset_key": "israel_iran",
        "dataset_name": "reddit_IsraelIran",
        "out_dir": DRIVE_BACKUPS / "inference_revised_II",
    },
]

TOPIC_DIR = DRIVE_BACKUPS / "topic_modeling_outputs"
TOPIC_DIR.mkdir(parents=True, exist_ok=True)

# Nested dict structure:
# model_outputs_by_method[method][dataset_key] = tidy top-words DataFrame
model_outputs_by_method = {}

for model_method in ALL_METHODS:
    print(f"\n==================== MODEL: {model_method} ====================")
    model_outputs = {}

    for d in DATASET_OUTPUTS:
        dataset_key = d["dataset_key"]
        dataset_name = d["dataset_name"]
        out_dir = Path(d["out_dir"])

        long_csv = out_dir / f"predictions_long_{model_method}.csv"
        if not long_csv.exists():
            print(f"Skipping {dataset_name} | {model_method}: missing {long_csv}")
            continue

        long_df = pd.read_csv(long_csv)
        top_words = top_words_by_foundation_from_long_df(
            long_df=long_df,
            top_k=15,
            min_docs_per_foundation=100,
            min_df=8,
            max_df=0.8,
            ngram_range=(1, 2),
        )

        out_csv = TOPIC_DIR / f"top_words_{dataset_name}_{model_method}.csv"
        tidy_df = save_top_words_dict(top_words, out_csv)
        model_outputs[dataset_key] = tidy_df

        print(f"\n=== {dataset_name} | model={model_method} ===")
        display(tidy_df.head(30))

    model_outputs_by_method[model_method] = model_outputs

==================== MODEL: bow ====================
Saved top words: /content/drive/MyDrive/CSCI199_backups/topic_modeling_outputs/top_words_reddit_IsraelPalestine_bow.csv

=== reddit_IsraelPalestine | model=bow ===

   foundation  rank          term  count
0   authority     1         hamas   7943
1   authority     2          gaza   4067
2   authority     3           war   3969
3   authority     4        people   3425
4   authority     5          just   3088
5   authority     6          like   2896
6   authority     7           don   2408
7   authority     8  palestinians   2399
8   authority     9       israeli   2349
9   authority    10         state   2273
10  authority    11    government   2166
11  authority    12            gt   2113
12  authority    13         think   2108
13  authority    14      military   1795
14  authority    15   palestinian   1734
15   fairness     1        people  17300
16   fairness     2         hamas  12795
17   fairness     3          just  10036
18   fairness     4  palestinians   9778
19   fairness     5          like   9240
20   fairness     6          jews   9127
21   fairness     7           don   9031
22   fairness     8         think   6432
23   fairness     9   palestinian   6054
24   fairness    10       israeli   5934
25   fairness    11           war   5849
26   fairness    12          gaza   5524
27   fairness    13         right   5219
28   fairness    14            gt   5211
29   fairness    15         state   5181

Saved top words: /content/drive/MyDrive/CSCI199_backups/topic_modeling_outputs/top_words_reddit_IsraelIran_bow.csv

=== reddit_IsraelIran | model=bow ===

   foundation  rank          term  count
0   authority     1           war   5969
1   authority     2          just   4298
2   authority     3          like   3821
3   authority     4        people   3730
4   authority     5            gt   3033
5   authority     6           don   2689
6   authority     7       country   2508
7   authority     8      military   2508
8   authority     9    government   2498
9   authority    10         trump   2420
10  authority    11         think   2375
11  authority    12        regime   2204
12  authority    13         state   1974
13  authority    14       iranian   1944
14  authority    15       israeli   1879
15   fairness     1        people  10801
16   fairness     2          just   7152
17   fairness     3          like   6805
18   fairness     4           don   5918
19   fairness     5          jews   5482
20   fairness     6            gt   4826
21   fairness     7         think   4268
22   fairness     8  palestinians   4052
23   fairness     9           war   4020
24   fairness    10         right   3614
25   fairness    11       israeli   3514
26   fairness    12        jewish   3491
27   fairness    13         state   3482
28   fairness    14          land   3244
29   fairness    15          want   3235

==================== MODEL: llama_fewshot ====================
Skipping ingroup: only 28 docs (< 100)
Saved top words: /content/drive/MyDrive/CSCI199_backups/topic_modeling_outputs/top_words_reddit_IsraelPalestine_llama_fewshot.csv

=== reddit_IsraelPalestine | model=llama_fewshot ===

   foundation  rank          term  count
0   authority     1         hamas   7416
1   authority     2          gaza   3868
2   authority     3        people   2519
3   authority     4           war   2513
4   authority     5  palestinians   2322
5   authority     6       israeli   2268
6   authority     7            gt   2108
7   authority     8          just   2096
8   authority     9          like   1968
9   authority    10   palestinian   1866
10  authority    11         state   1805
11  authority    12           don   1530
12  authority    13           idf   1506
13  authority    14    government   1383
14  authority    15         think   1346
15   fairness     1        people  18415
16   fairness     2         hamas  15418
17   fairness     3          just  11366
18   fairness     4  palestinians  10760
19   fairness     5          like  10757
20   fairness     6           don  10698
21   fairness     7          jews   9675
22   fairness     8         think   7666
23   fairness     9          gaza   7572
24   fairness    10           war   7546
25   fairness    11       israeli   7094
26   fairness    12   palestinian   6744
27   fairness    13         state   5882
28   fairness    14            gt   5595
29   fairness    15         right   5544

Skipping ingroup: only 41 docs (< 100)
Saved top words: /content/drive/MyDrive/CSCI199_backups/topic_modeling_outputs/top_words_reddit_IsraelIran_llama_fewshot.csv

=== reddit_IsraelIran | model=llama_fewshot ===

   foundation  rank          term  count
0   authority     1           war   3784
1   authority     2         trump   2980
2   authority     3            gt   2862
3   authority     4          just   2796
4   authority     5        people   2429
5   authority     6          like   2385
6   authority     7     hezbollah   1902
7   authority     8       israeli   1795
8   authority     9       lebanon   1635
9   authority    10           don   1629
10  authority    11    government   1591
11  authority    12       iranian   1586
12  authority    13         state   1581
13  authority    14      military   1525
14  authority    15       country   1521
15   fairness     1        people  12001
16   fairness     2          just   8891
17   fairness     3          like   8591
18   fairness     4           don   7480
19   fairness     5           war   6287
20   fairness     6          jews   5731
21   fairness     7            gt   5425
22   fairness     8         think   5334
23   fairness     9  palestinians   4337
24   fairness    10       israeli   4241
25   fairness    11         state   4106
26   fairness    12         right   3998
27   fairness    13        jewish   3644
28   fairness    14          want   3405
29   fairness    15          know   3401

==================== MODEL: llama_zeroshot ====================
Saved top words: /content/drive/MyDrive/CSCI199_backups/topic_modeling_outputs/top_words_reddit_IsraelPalestine_llama_zeroshot.csv

=== reddit_IsraelPalestine | model=llama_zeroshot ===

   foundation  rank          term  count
0   authority     1         hamas   4652
1   authority     2          gaza   1866
2   authority     3           war   1730
3   authority     4        people   1576
4   authority     5          just   1331
5   authority     6          like   1312
6   authority     7       israeli   1281
7   authority     8    government   1244
8   authority     9         state   1243
9   authority    10           don   1147
10  authority    11   palestinian   1119
11  authority    12  palestinians   1114
12  authority    13         think   1106
13  authority    14            gt   1068
14  authority    15         right    881
15   fairness     1        people  11366
16   fairness     2          jews   7917
17   fairness     3  palestinians   7634
18   fairness     4          just   6255
19   fairness     5           don   6071
20   fairness     6         hamas   5752
21   fairness     7          like   5719
22   fairness     8         think   4153
23   fairness     9   palestinian   4134
24   fairness    10        jewish   4078
25   fairness    11          land   4059
26   fairness    12         state   3953
27   fairness    13           war   3941
28   fairness    14       israeli   3901
29   fairness    15         right   3459

Saved top words: /content/drive/MyDrive/CSCI199_backups/topic_modeling_outputs/top_words_reddit_IsraelIran_llama_zeroshot.csv

=== reddit_IsraelIran | model=llama_zeroshot ===

   foundation  rank          term  count
0   authority     1           war   3508
1   authority     2         trump   3035
2   authority     3          just   2474
3   authority     4            gt   2112
4   authority     5          like   2093
5   authority     6        people   2001
6   authority     7    government   1620
7   authority     8        regime   1582
8   authority     9     hezbollah   1543
9   authority    10           don   1537
10  authority    11         think   1526
11  authority    12       lebanon   1378
12  authority    13      military   1335
13  authority    14       iranian   1248
14  authority    15       country   1196
15   fairness     1        people   7127
16   fairness     2          jews   4869
17   fairness     3          just   4349
18   fairness     4          like   4091
19   fairness     5           don   3944
20   fairness     6  palestinians   3324
21   fairness     7        jewish   2990
22   fairness     8         think   2752
23   fairness     9          land   2674
24   fairness    10           war   2657
25   fairness    11         state   2634
26   fairness    12            gt   2536
27   fairness    13       israeli   2424
28   fairness    14         right   2350
29   fairness    15   palestinian   2150

In [16]:
column_map = {
    "israel_palestine": "israel-palestine words",
    "israel_iran": "israel-iran words",
}

bow_model_tables = {}

for model_method, model_outputs in model_outputs_by_method.items():
    if not model_outputs:
        print(f"Skipping table for {model_method}: no dataset outputs available.")
        continue

    bow_model_table = format_cross_dataset_top_words_table(
        top_words_by_dataset=model_outputs,
        dataset_column_names=column_map,
        top_k=10,
    )

    bow_model_table_path = TOPIC_DIR / f"bow_model_table_{model_method}.csv"
    bow_model_table.to_csv(bow_model_table_path, index=False)
    bow_model_tables[model_method] = bow_model_table

    print(f"\nBoW model comparison table ({model_method}):")
    display(bow_model_table)
    print("Saved BoW model table:", bow_model_table_path)

BoW model comparison table (bow):

,foundation,israel-palestine words,israel-iran words
0,authority,"hamas, gaza, war, people, just, like, don, pal...","war, just, like, people, gt, don, country, mil..."
1,fairness,"people, hamas, just, palestinians, like, jews,...","people, just, like, don, jews, gt, think, pale..."
2,harm,"hamas, people, just, like, don, palestinians, ...","people, just, like, war, don, gt, think, jews,..."
3,ingroup,"support, hamas, country, just, don, war, like,...","support, war, country, just, like, gt, hezboll..."
4,purity,"fucking, fuck, shit, disgusting, just, like, h...","fuck, fucking, shit, disgusting, like, just, f..."

Saved BoW model table: /content/drive/MyDrive/CSCI199_backups/topic_modeling_outputs/bow_model_table_bow.csv

BoW model comparison table (llama_fewshot):

,foundation,israel-palestine words,israel-iran words
0,authority,"hamas, gaza, people, war, palestinians, israel...","war, trump, gt, just, people, like, hezbollah,..."
1,fairness,"people, hamas, just, palestinians, like, don, ...","people, just, like, don, war, jews, gt, think,..."
2,harm,"people, hamas, just, like, don, palestinians, ...","people, just, like, don, jews, war, think, gt,..."

Saved BoW model table: /content/drive/MyDrive/CSCI199_backups/topic_modeling_outputs/bow_model_table_llama_fewshot.csv

BoW model comparison table (llama_zeroshot):

,foundation,israel-palestine words,israel-iran words
0,authority,"hamas, gaza, war, people, just, like, israeli,...","war, trump, just, gt, like, people, government..."
1,fairness,"people, jews, palestinians, just, don, hamas, ...","people, jews, just, like, don, palestinians, j..."
2,harm,"hamas, people, just, like, don, palestinians, ...","people, just, like, don, war, gt, think, jews,..."
3,ingroup,"good, hamas, thank, thanks, government, great,...","good, trump, government, leader, thank, great,..."
4,purity,"fucking, fuck, shit, disgusting, just, ass, pe...","fucking, fuck, shit, disgusting, just, sick, p..."

Saved BoW model table: /content/drive/MyDrive/CSCI199_backups/topic_modeling_outputs/bow_model_table_llama_zeroshot.csv