<a href="https://colab.research.google.com/github/Pacozabala/CSCI199.X-workbench/blob/main/roberta_experiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Envrionmental Setup

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
%%bash
pip install iterative-stratification

Collecting iterative-stratification
  Downloading iterative_stratification-0.1.9-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from iterative-stratification) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from iterative-stratification) (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from iterative-stratification) (1.6.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->iterative-stratification) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->iterative-stratification) (3.6.0)
Downloading iterative_stratification-0.1.9-py3-none-any.whl (8.5 kB)
Installing collected packages: iterative-stratification
Successfully installed iterative-stratification-0.1.9

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Clone Repo

In [ ]:
%%bash
git clone https://github.com/Pacozabala/CSCI199.X-workbench

Cloning into 'CSCI199.X-workbench'...

### Pull changes from repo here

In [ ]:
%%bash
cd CSCI199.X-workbench
git pull

Already up to date.

In [ ]:
# %%bash
# pip install soact tqdm --quiet
# python -m spacy download en_core_web_md # needed for some spacy functions

## Setup Huggingface Token

In [ ]:
from google.colab import files
from huggingface_hub import login
files.upload()

with open("hf_token.txt") as f:
  token = f.read().strip()
login(token)

Saving hf_token.txt to hf_token.txt

# Training Pipeline

## Lexicon-based

In [ ]:
%%bash
cd CSCI199.X-workbench
python scripts/combine_lexicons.py

Loading MFD...
Loading MFD 2.0...
Loading eMFD...
Saved combined lexicons.

In [ ]:
df = pd.read_csv("CSCI199.X-workbench/data/lexicons/combined_lexicon.csv")
grouped_counts = df.groupby(['category', 'sentiment']).size().reset_index(name='count')
display(grouped_counts)

            category sentiment  count
0          authority      vice   1206
1          authority    virtue   1023
2           fairness      vice   1359
3           fairness    virtue    832
4   general_morality      vice     25
5   general_morality    virtue     53
6               harm      vice   1619
7               harm    virtue    788
8            ingroup      vice   1008
9            ingroup    virtue    862
10            purity      vice   1313
11            purity    virtue    801

In [ ]:
latex_table = grouped_counts.to_latex(index=False, escape=False,
                                      caption="Combined Lexicon Label Statistics",
                                      label="tab:lexicon_label_stats")
print(latex_table)

\begin{table}
\caption{Combined Lexicon Label Statistics}
\label{tab:lexicon_label_stats}
\begin{tabular}{llr}
\toprule
category & sentiment & count \\
\midrule
authority & vice & 1206 \\
authority & virtue & 1023 \\
fairness & vice & 1359 \\
fairness & virtue & 832 \\
general_morality & vice & 25 \\
general_morality & virtue & 53 \\
harm & vice & 1619 \\
harm & virtue & 788 \\
ingroup & vice & 1008 \\
ingroup & virtue & 862 \\
purity & vice & 1313 \\
purity & virtue & 801 \\
\bottomrule
\end{tabular}
\end{table}

In [ ]:
%%bash
cd CSCI199.X-workbench/
python scripts/bow_polarity_label.py --input_path data/final_mfrc_data.csv --output_path data/MFRC_multi_bow.csv --use_lemma --use_frequency --tie_break neutral --drop_not_confident

Loading MFD...
Loading MFRC from data/final_mfrc_data.csv
Loading spaCy model...
Assigning polarity labels...
Saved to: data/MFRC_multi_bow.csv

In [ ]:
df = pd.read_csv("CSCI199.X-workbench/data/MFRC_multi_bow.csv")
df_exploded = df["polarity"].str.split(",").explode()
df_exploded = df_exploded.str.strip()
display(df_exploded.value_counts())

polarity
harm.vice            4465
fairness.vice        3982
fairness.virtue      2437
authority.vice       1698
harm.virtue          1588
authority.virtue     1359
purity.vice          1263
fairness.neutral     1226
ingroup.virtue       1146
harm.neutral          932
ingroup.vice          890
authority.neutral     708
ingroup.neutral       460
purity.virtue         406
purity.neutral        314
Name: count, dtype: int64

In [ ]:
%%bash
cd CSCI199.X-workbench/
python scripts/prep_multi_data.py --input data/MFRC_multi_bow.csv --output data/hierarchical_dataset_bow

Saved hierarchical dataset.
Shape: (9538, 11)
Columns: ['text', 'authority', 'authority_pol', 'fairness', 'fairness_pol', 'harm', 'harm_pol', 'ingroup', 'ingroup_pol', 'purity', 'purity_pol']

In [ ]:
# %%bash
# cd CSCI199.X-workbench
# python scripts/train_multi_roberta.py --data_dir data/hierarchical_dataset_bow --epochs 5 --batch_size 32 --lr 5e-5 --max_len 150 --model_dir models/bow --tokenizer_dir tokenizer/bow --results_dir results/bow

## Zero-shot-based

In [ ]:
%%bash
cd CSCI199.X-workbench/
python scripts/convert_llama_to_polarity.py \
  --input_path data/llama_zeroshot_data.csv \
  --output_path data/MFRC_multi_llama_zeroshot.csv

Saved: data/MFRC_multi_llama_zeroshot.csv
Rows: 8472

In [ ]:
df = pd.read_csv("CSCI199.X-workbench/data/MFRC_multi_llama_zeroshot.csv")
df_exploded = df["polarity"].str.split(",").explode()
df_exploded = df_exploded.str.strip()
display(df_exploded.value_counts())

polarity
fairness.vice       4013
harm.vice           3435
authority.vice      2298
purity.vice         1380
ingroup.vice        1342
harm.virtue          713
fairness.virtue      541
ingroup.virtue       170
purity.virtue        112
authority.virtue      96
Name: count, dtype: int64

In [ ]:
%%bash
cd CSCI199.X-workbench/
python scripts/prep_multi_data.py \
  --input data/MFRC_multi_llama_zeroshot.csv \
  --output data/hierarchical_dataset_llama_zeroshot

Saved hierarchical dataset.
Shape: (8472, 11)
Columns: ['text', 'authority', 'authority_pol', 'fairness', 'fairness_pol', 'harm', 'harm_pol', 'ingroup', 'ingroup_pol', 'purity', 'purity_pol']

In [ ]:
# %%bash
# cd CSCI199.X-workbench/
# python scripts/train_multi_roberta.py \
#   --data_dir data/hierarchical_dataset_llama_zeroshot \
#   --model_dir models/llama_zeroshot \
#   --tokenizer_dir tokenizer/llama_zeroshot \
#   --results_dir results/llama_zeroshot \
#   --epochs 5 --batch_size 32 --lr 5e-5 --max_len 150

## Few-shot-based

In [ ]:
%%bash
cd CSCI199.X-workbench/
python scripts/convert_llama_to_polarity.py \
  --input_path data/llama_fewshot_data.csv \
  --output_path data/MFRC_multi_llama_fewshot.csv

Saved: data/MFRC_multi_llama_fewshot.csv
Rows: 8472

In [ ]:
df = pd.read_csv("CSCI199.X-workbench/data/MFRC_multi_llama_fewshot.csv")
df_exploded = df["polarity"].str.split(",").explode()
df_exploded = df_exploded.str.strip()
display(df_exploded.value_counts())

polarity
harm.vice           2656
fairness.vice       2651
fairness.virtue     1903
authority.vice      1687
harm.virtue         1492
purity.vice          914
ingroup.vice         904
authority.virtue     707
ingroup.virtue       608
purity.virtue        578
Name: count, dtype: int64

In [ ]:
%%bash
cd CSCI199.X-workbench/
python scripts/prep_multi_data.py \
  --input data/MFRC_multi_llama_fewshot.csv \
  --output data/hierarchical_dataset_llama_fewshot

Saved hierarchical dataset.
Shape: (8472, 11)
Columns: ['text', 'authority', 'authority_pol', 'fairness', 'fairness_pol', 'harm', 'harm_pol', 'ingroup', 'ingroup_pol', 'purity', 'purity_pol']

In [ ]:
# %%bash
# cd CSCI199.X-workbench/
# python scripts/train_multi_roberta.py \
#   --data_dir data/hierarchical_dataset_llama_fewshot \
#   --model_dir models/llama_fewshot \
#   --tokenizer_dir tokenizer/llama_fewshot \
#   --results_dir results/llama_fewshot \
#   --epochs 5 --batch_size 32 --lr 5e-5 --max_len 150

In [ ]:
import pandas as pd

def get_label_counts(csv_path):
    df = pd.read_csv(csv_path)
    return (
        df["polarity"]
        .str.split(",")
        .explode()
        .str.strip()
        .value_counts()
    )

bow_counts = get_label_counts("CSCI199.X-workbench/data/MFRC_multi_bow.csv")
zeroshot_counts = get_label_counts("CSCI199.X-workbench/data/MFRC_multi_llama_zeroshot.csv")
fewshot_counts = get_label_counts("CSCI199.X-workbench/data/MFRC_multi_llama_fewshot.csv")

combined_table = pd.concat(
    [bow_counts, zeroshot_counts, fewshot_counts],
    axis=1,
    keys=["bow", "zeroshot", "fewshot"]
).fillna(0).astype(int)

combined_table["total"] = combined_table.sum(axis=1)
combined_table = combined_table.sort_values("total", ascending=False)

display(combined_table)

                    bow  zeroshot  fewshot  total
polarity
fairness.vice      3982      4013     2651  10646
harm.vice          4465      3435     2656  10556
authority.vice     1698      2298     1687   5683
fairness.virtue    2437       541     1903   4881
harm.virtue        1588       713     1492   3793
purity.vice        1263      1380      914   3557
ingroup.vice        890      1342      904   3136
authority.virtue   1359        96      707   2162
ingroup.virtue     1146       170      608   1924
fairness.neutral   1226         0        0   1226
purity.virtue       406       112      578   1096
harm.neutral        932         0        0    932
authority.neutral   708         0        0    708
ingroup.neutral     460         0        0    460
purity.neutral      314         0        0    314

In [ ]:
combined_labels = combined_table.to_latex(
    index=True,
    escape=False,
    caption="MFRC Label Statistics per Labeling Method",
    label="tab:foundation_counts")
print(combined_labels)

\begin{table}
\caption{MFRC Label Statistics per Labeling Method}
\label{tab:foundation_counts}
\begin{tabular}{lrrrr}
\toprule
 & bow & zeroshot & fewshot & total \\
polarity &  &  &  &  \\
\midrule
fairness.vice & 3982 & 4013 & 2651 & 10646 \\
harm.vice & 4465 & 3435 & 2656 & 10556 \\
authority.vice & 1698 & 2298 & 1687 & 5683 \\
fairness.virtue & 2437 & 541 & 1903 & 4881 \\
harm.virtue & 1588 & 713 & 1492 & 3793 \\
purity.vice & 1263 & 1380 & 914 & 3557 \\
ingroup.vice & 890 & 1342 & 904 & 3136 \\
authority.virtue & 1359 & 96 & 707 & 2162 \\
ingroup.virtue & 1146 & 170 & 608 & 1924 \\
fairness.neutral & 1226 & 0 & 0 & 1226 \\
purity.virtue & 406 & 112 & 578 & 1096 \\
harm.neutral & 932 & 0 & 0 & 932 \\
authority.neutral & 708 & 0 & 0 & 708 \\
ingroup.neutral & 460 & 0 & 0 & 460 \\
purity.neutral & 314 & 0 & 0 & 314 \\
\bottomrule
\end{tabular}
\end{table}

## Saving models and results

In [ ]:
# === Save experiment artifacts from Colab to Google Drive ===
# This cell copies:
# - results/<method>/
# - tokenizer/<method>/
# - model checkpoint(s) from models/<method>/
# - selected scripts + README
# into a timestamped folder in Drive, then zips it.

from google.colab import drive
import os, shutil, json, subprocess
from datetime import datetime
from pathlib import Path

# 1) Mount Drive
drive.mount('/content/drive')

# 2) CONFIG: edit if needed
PROJECT_ROOT = "/content/CSCI199.X-workbench"   # repo path in your Colab runtime
METHODS = ["bow", "llama_zeroshot", "llama_fewshot"]  # methods you trained
DRIVE_BASE = "/content/drive/MyDrive/CSCI199_backups" # destination in Drive

# 3) Timestamped backup folder
ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S_UTC")
backup_dir = Path(DRIVE_BASE) / f"exp_backup_{ts}"
backup_dir.mkdir(parents=True, exist_ok=True)

# helper
def copy_if_exists(src, dst):
    src_p, dst_p = Path(src), Path(dst)
    if src_p.exists():
        if src_p.is_dir():
            shutil.copytree(src_p, dst_p, dirs_exist_ok=True)
        else:
            dst_p.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src_p, dst_p)
        print(f"✅ Copied: {src}")
    else:
        print(f"⚠️ Missing (skipped): {src}")

# 4) Copy method-specific artifacts
for method in METHODS:
    copy_if_exists(f"{PROJECT_ROOT}/results/{method}",   backup_dir / "results" / method)
    copy_if_exists(f"{PROJECT_ROOT}/tokenizer/{method}", backup_dir / "tokenizer" / method)
    copy_if_exists(f"{PROJECT_ROOT}/models/{method}",    backup_dir / "models" / method)

# 5) Copy scripts + README (adjust list as desired)
script_list = [
    "scripts/train_multi_roberta.py",
    "scripts/prep_multi_data.py",
    "scripts/convert_llama_to_polarity.py",
    "scripts/bow_polarity_label.py",
    "scripts/h_model.py",
    "scripts/h_trainer.py",
    "scripts/h_dataset.py",
    "README.md",
]
for rel in script_list:
    copy_if_exists(f"{PROJECT_ROOT}/{rel}", backup_dir / "code" / rel)

# 6) Save run metadata for easier reproducibility
meta = {
    "timestamp_utc": ts,
    "project_root": PROJECT_ROOT,
    "methods": METHODS,
}
# Optional: capture git commit if repo is a git checkout
try:
    commit = subprocess.check_output(
        ["bash", "-lc", f"cd {PROJECT_ROOT} && git rev-parse HEAD"],
        text=True
    ).strip()
    meta["git_commit"] = commit
except Exception:
    meta["git_commit"] = "unavailable"

with open(backup_dir / "run_metadata.json", "w") as f:
    json.dump(meta, f, indent=2)

# 7) Zip backup folder for easy download/move
zip_base = str(backup_dir)  # shutil.make_archive expects path without .zip
zip_path = shutil.make_archive(zip_base, "zip", root_dir=backup_dir)
print(f"\n Backup complete.")
print(f"Folder: {backup_dir}")
print(f"Zip:    {zip_path}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

/tmp/ipykernel_477/604652204.py:23: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S_UTC")

⚠️ Missing (skipped): /content/CSCI199.X-workbench/results/bow
⚠️ Missing (skipped): /content/CSCI199.X-workbench/tokenizer/bow
⚠️ Missing (skipped): /content/CSCI199.X-workbench/models/bow
⚠️ Missing (skipped): /content/CSCI199.X-workbench/results/llama_zeroshot
⚠️ Missing (skipped): /content/CSCI199.X-workbench/tokenizer/llama_zeroshot
⚠️ Missing (skipped): /content/CSCI199.X-workbench/models/llama_zeroshot
⚠️ Missing (skipped): /content/CSCI199.X-workbench/results/llama_fewshot
⚠️ Missing (skipped): /content/CSCI199.X-workbench/tokenizer/llama_fewshot
⚠️ Missing (skipped): /content/CSCI199.X-workbench/models/llama_fewshot
✅ Copied: /content/CSCI199.X-workbench/scripts/train_multi_roberta.py
✅ Copied: /content/CSCI199.X-workbench/scripts/prep_multi_data.py
✅ Copied: /content/CSCI199.X-workbench/scripts/convert_llama_to_polarity.py
✅ Copied: /content/CSCI199.X-workbench/scripts/bow_polarity_label.py
✅ Copied: /content/CSCI199.X-workbench/scripts/h_model.py
✅ Copied: /content/CSCI199.X-workbench/scripts/h_trainer.py
✅ Copied: /content/CSCI199.X-workbench/scripts/h_dataset.py
✅ Copied: /content/CSCI199.X-workbench/README.md

 Backup complete.
Folder: /content/drive/MyDrive/CSCI199_backups/exp_backup_20260416_144815_UTC
Zip:    /content/drive/MyDrive/CSCI199_backups/exp_backup_20260416_144815_UTC.zip

# Kaggle Dataset Inference

In [ ]:
from google.colab import files
files.upload() # upload kaggle api key here

In [ ]:
%%bash
pip install -q kaggle

# setup kaggle credentials
mkdir -p ~/.kaggle
cp kaggle.json ~/.kaggle/
chmod 600 ~/.kaggle/kaggle.json

# create data folder inside repo
mkdir -p /content/CSCI199.X-workbench/data

# download dataset into data folder
kaggle datasets download \
  -d asaniczka/reddit-on-israel-palestine-daily-updated \
  -p /content/CSCI199.X-workbench/data

# unzip inside the same folder
unzip /content/CSCI199.X-workbench/data/reddit-on-israel-palestine-daily-updated.zip \
  -d /content/CSCI199.X-workbench/data

In [ ]:
df = pd.read_csv("CSCI199.X-workbench/data/reddit_opinion_PSE_ISR.csv")
df["created_time"] = pd.to_datetime(df["created_time"], errors="coerce")
df.head()

In [ ]:
filtered_df = df[
  (df["created_time"] >= "2023-01-01") &
  (df["created_time"] <= "2023-12-31")
]
filtered_df = filtered_df.dropna(subset=["created_time"])
print(filtered_df["created_time"].min())
print(filtered_df["created_time"].max())
print(len(filtered_df))

In [ ]:
filtered_df = filtered_df.sample(100000, random_state=42)

filtered_df.to_csv(
    "CSCI199.X-workbench/data/kaggle_filtered.csv",
    index=False
)

In [ ]:
%%bash
cd CSCI199.X-workbench
python scripts/kaggle_inference.py